name: Awesome Research Group
url: http://awesome.example.edu

exclude: [README.md, Makefile]

# colorize code snippets with the pygments module
markdown: KramdownPygments
kramdown:
    input: GFM

# The path structure for blog posts.
permalink: pretty

include: ['_pages','img','notebooks']

# Number of news stories on the front page.
front_page_news: 3

# Base pathname for links.
baseurl: /

# Navigation bar links.
navigation:
    - title: About Me
      link: 
    - title: Resume
      link: Resume
    - title: Log
      link: Log
    - title: Projects
      link: Projects

